parameters:
    webtown_kunstmaan_extension.max_page_insertion_depth: 3

services:
    webtown_kunstmaan_extension.page_insert.twig.extension:
        class: Webtown\KunstmaanExtensionBundle\Twig\Extension\PageInsertTwigExtension
        arguments:
            - "@doctrine"
            - "@kunstmaan_pageparts.twig.extension"
            - "%webtown_kunstmaan_extension.max_page_insertion_depth%"
        tags:
            - { name: twig.extension }

    webtown_kunstmaan_extension.page_insert.admin_form_type:
        class: Webtown\KunstmaanExtensionBundle\Form\PageParts\InsertPagePagePartAdminType
        arguments:
            - "@request_stack"
            - "@doctrine"
            - "@kunstmaan_page_part.page_part_configuration_reader"
        tags:
            - { name: form.type, alias: page_insert_page_part_type }

    webtown_kunstmaan_extension.translation.kunstmaan_extractor:
        class: Webtown\KunstmaanExtensionBundle\Translation\Extraction\File\KunstmaanExtractor
        arguments:
            - "@jms_translation.doc_parser"
        tags:
            - { name: jms_translation.file_visitor }

    webtown_kunstmaan_extension.translation.kunstmaan_yml_extractor:
        class: Webtown\KunstmaanExtensionBundle\Translation\Extraction\File\OriginalTranslationsYmlExtractor
        tags:
            - { name: jms_translation.file_visitor }

    webtown_kunstmaan_extension.translation.menu_extractor:
        class: Webtown\KunstmaanExtensionBundle\Translation\Extraction\File\MenuExtractor
        arguments:
            - "@jms_translation.doc_parser"
        tags:
            - { name: jms_translation.file_visitor }

    webtown_kunstmaan_extension.settings_menu_adaptor:
        class: Webtown\KunstmaanExtensionBundle\Helper\Menu\SettingsMenuAdaptor
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    webtown_kunstmaan_extension.cache_manager:
        class: Webtown\KunstmaanExtensionBundle\HttpCache\Manager
        arguments:
            - "%kernel.cache_dir%"
            - "@filesystem"
            - "@?fos_http_cache.cache_manager"

    webtown_kunstmaan_extension.cache_purge_subscriber:
        class: Webtown\KunstmaanExtensionBundle\EventListener\CachePurgeSubscriber
        lazy: true
        arguments:
            - "@webtown_kunstmaan_extension.cache_manager"
            - "@?session"
        tags:
            - { name: doctrine.event_subscriber }

    # Optimalizálás végett adjuk át a container-t!
    webtown_kunstmaan_extension.search_subscriber:
        class: Webtown\KunstmaanExtensionBundle\EventListener\SearchSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber }

    webtown_kunstmaan_extension.searchable_entity_configuration:
        class: Webtown\KunstmaanExtensionBundle\Configuration\SearchableEntityConfiguration
        lazy:  true
        arguments:
            - '%kunstmaan_node_search.indexname%' # direkt használjuk ugyanazt, mint a NodeSearch! Különben nem találja a normál keresés.
            - '%kunstmaan_node_search.indextype%' # direkt használjuk ugyanazt, mint a NodeSearch! Különben nem találja a normál keresés.
            - '@kunstmaan_search.search'
            - '@kunstmaan_admin.domain_configuration'
            - '%analyzer_languages%'
            - '@doctrine'
            - '@event_dispatcher'
            - '@?doctrine_mongodb'
        tags:
            - { name: kunstmaan_search.search_configuration, alias: Entity }

    webtown_kunstmaan_extension.search.twig.extension:
        class: Webtown\KunstmaanExtensionBundle\Twig\Extension\SearchTwigExtension
        arguments:
            - "@twig.extension.routing"
        tags:
            - { name: twig.extension }

    webtown_kunstmaan_extension.user_edit:
        class: Webtown\KunstmaanExtensionBundle\User\UserEditService
        arguments:
          - "@doctrine"
          - "@security.password_encoder"
